version: '3'

services:
  university:
    restart: always
    build: ./university
    ports:
      - "7274:80"
    depends_on:
      - mssql
  mssql:
    restart: always
    image: mcr.microsoft.com/mssql/server
    container_name: mssql-db
    environment:
      SA_PASSWORD: StrongPassword123!
      ACCEPT_EULA: Y
      MSSQL_DB_NAME: University
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/lib/mssql
  adminer:
    image: adminer
    restart: always
    ports:
      - 4261:8080
    depends_on:
      - mssql

volumes:
  mssql_data:

  